---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family | lower }}.yml"

- import_tasks: install-redhat.yml
  when: "ansible_os_family | lower == 'redhat'"

- import_tasks: install-debian.yml
  when: "ansible_os_family | lower == 'debian'"
